- name: Get the active Firefox profile from profiles.ini
  register: profiles_info
  changed_when: false
  ansible.builtin.command: grep -E '^Path|^Default' ~/.mozilla/firefox/profiles.ini

- name: Find the active profile path
  loop: "{{ range(1, profiles_info['stdout_lines'] | length) | list }}"
  when: "'Default=1' in profiles_info['stdout_lines'][item]"
  ansible.builtin.set_fact:
    firefox_profile_dir: "{{ profiles_info['stdout_lines'][item | int - 1] | regex_replace('Path=', '') }}"

- name: Ensure Firefox font size is 20
  ansible.builtin.lineinfile:
    path: "~/.mozilla/firefox/{{ firefox_profile_dir }}/prefs.js"
    line: 'user_pref("font.size.variable.x-western", 20);'
    create: true

- name: Ensure bookmarks backup is copied
  ansible.builtin.copy:
    src: bookmarks.json
    dest: "~/.mozilla/firefox/{{ firefox_profile_dir }}/bookmarkbackups/bookmarks_backup.json"

- name: Start Firefox to apply bookmarks from backup
  ansible.builtin.shell: "firefox & sleep 20 && pkill firefox"
  async: 1
  poll: 0

